name: Fast-Forward

on: 
  issue_comment:
    types: [created]
  push:
  pull_request:
  # So that the `dirtyLabel` is removed if conflicts are resolve
  # We recommend `pull_request_target` so that github secrets are available.
  # In `pull_request` we wouldn't be able to change labels of fork PRs
  ## pull_request_target:
  ##   types: [synchronize]

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: APN-Pucky/fast-forward-action@main
        if: ${{ github.actor != 'dependabot[bot]' }}
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SSH_PRIVATE_KEY: ${{ secrets.GH_SSH }}
